version: "3"
services:
  reindexer:
    container_name: ${DB_NAME}
    image: reindexer/reindexer:latest
  aggregator:
    container_name: ${AGGREGATOR_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"