version: "3"
services:
  reindexer:
    container_name: "reindexer"
    image: reindexer/reindexer:latest
  aggregator:
    container_name: "server"
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8080:8080"
  postgres:
    container_name: "postgres"
    ports:
      - "5432:5432"
    build:
      context: .
      dockerfile: postgres.Dockerfile
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - postgres.env
