version: "3"
services:
  postgres_auth:
    container_name: "postgres_auth"
    ports:
      - "5431:5432"
    build:
      context: .
      dockerfile: authPostgres.Dockerfile
    volumes:
      - pg_authData:/var/lib/postgresql/data
    env_file:
      - authPostgres.env
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
  reindexer:
    container_name: "reindexer"
    image: reindexer/reindexer:latest
    ports:
      - "6534:6534"
      - "9088:9088"
  aggregator:
    container_name: "server"
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8080:8080"
  postgres:
    container_name: "postgres"
    ports:
      - "5432:5432"
    build:
      context: .
      dockerfile: postgres.Dockerfile
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - postgres.env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  pg_authData:
  pg_data:
