// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/add/": {
            "post": {
                "description": "Based on the body of POST request add film to the DB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "Add film to the DB",
                "parameters": [
                    {
                        "description": "film model",
                        "name": "film",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Film"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Film"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "405": {
                        "description": "Method Not Allowed"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/all/": {
            "get": {
                "description": "Get every available film from the DB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "films"
                ],
                "summary": "Get all the films from the DB",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Film"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "405": {
                        "description": "Method Not Allowed"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/delete/": {
            "delete": {
                "description": "Delete film from both cache and main repositories based on the user's provided filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "Delete film",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Film title",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Film genre",
                        "name": "genre",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Film release date",
                        "name": "released_year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DeleteRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "405": {
                        "description": "Method Not Allowed"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "api.DeleteRequest": {
            "type": "object",
            "properties": {
                "genre": {
                    "type": "string"
                },
                "released_year": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.Film": {
            "type": "object",
            "properties": {
                "crew": {
                    "$ref": "#/definitions/general.Crew"
                },
                "genre": {
                    "type": "string"
                },
                "released_year": {
                    "type": "integer"
                },
                "revenue": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "general.Actor": {
            "type": "object",
            "properties": {
                "birthdate": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "general.Crew": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/general.Actor"
                    }
                },
                "producers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/general.Producer"
                    }
                }
            }
        },
        "general.Producer": {
            "type": "object",
            "properties": {
                "birthdate": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Films Aggregator",
	Description:      "API Server for Films Aggregator application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
